# Generated by Django 4.2.2 on 2023-06-16 12:17

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import staff.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('position_at_work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=254, null=True, upload_to=staff.models.upload_to)),
                ('first_name', models.CharField(max_length=128, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=128, verbose_name='Отчество')),
                ('employment_date', models.DateField(auto_now_add=True, verbose_name='Дата приема на работу')),
                ('wage', models.PositiveIntegerField(verbose_name='Заработная плата')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate', to='staff.staff', verbose_name='Начальник')),
                ('position_at_work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='position_at_work.positionatwork', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
